package main

import (
	"bufio"
	_ "embed"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

//go:embed .vigilignore.example
var defaultIgnore string

var version = "dev" // set by ldflags during build

const (
	markerStart = `<!-- PROJECT-STRUCTURE-START *** DO NOT EDIT OR DELETE THIS SECTION *** Auto-generated by vigil -->`
	markerEnd   = `<!-- PROJECT-STRUCTURE-END *** DO NOT EDIT OR DELETE THIS SECTION *** -->`
)

var defaultExclusions = []string{
	"node_modules", "dist", "build", "target", ".wrangler", ".git",
	"_old", "_backup", ".idea", ".vscode", ".DS_Store", "coverage",
	"vendor", ".venv", "venv", "__pycache__", "*.pyc",
	"*.log", "*.swp", "*.swo", "*.tsbuildinfo",
	"pnpm-lock.yaml", "package-lock.json", "go.sum",
	".env", ".env.*", ".dev.vars",
	"*.db", "*.db-shm", "*.db-wal",
}

type Config struct {
	RootDir  string
	DryRun   bool
	Verbose  bool
	ExecCmd  string
	ExecArgs []string
}

type treeEntry struct {
	path  string
	isDir bool
	depth int
	name  string
}

func main() {
	cfg, err := parseArgs()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	if err := run(cfg); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func parseArgs() (*Config, error) {
	cfg := &Config{
		RootDir: ".",
		ExecCmd: "claude",
	}

	args := os.Args[1:]
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--dry-run", "-n":
			cfg.DryRun = true
		case "--verbose", "-v":
			cfg.Verbose = true
		case "--exec", "-e":
			if i+1 >= len(args) {
				return nil, fmt.Errorf("--exec requires an argument")
			}
			cfg.ExecCmd = args[i+1]
			i++
		case "--claude", "-c":
			cfg.ExecCmd = "claude"
		case "--opencode", "-o":
			cfg.ExecCmd = "opencode"
		case "--openclaw":
			cfg.ExecCmd = "openclaw"
		case "--hermes":
			cfg.ExecCmd = "hermes"
		case "--droid":
			cfg.ExecCmd = "droid"
		case "--crush":
			cfg.ExecCmd = "crush"
		case "--goose":
			cfg.ExecCmd = "goose"
		case "--cursor", "-r":
			cfg.ExecCmd = "cursor"
		case "--aider", "-a":
			cfg.ExecCmd = "aider"
		case "--no-launch", "-N":
			cfg.ExecCmd = ""
		case "--version", "-V":
			printVersion()
			os.Exit(0)
		case "--help", "-h":
			printHelp()
			os.Exit(0)
		default:
			cfg.ExecArgs = args[i:]
			i = len(args)
		}
	}

	return cfg, nil
}

func printHelp() {
	fmt.Printf(`vigil - Generate project structure and inject into markdown files

Usage:
  vigil                    Generate structure and inject into CLAUDE.md/AGENTS.md
  vigil "your prompt"      Launch CLI with a prompt

CLI selection:
  -c, --claude             Launch Claude Code (default)
  -a, --aider              Launch Aider
  -r, --cursor             Launch Cursor
  -o, --opencode           Launch OpenCode
     --openclaw            Launch OpenClaw
     --hermes              Launch Hermes
     --droid               Launch Droid
     --crush               Launch Crush
     --goose               Launch Goose
  -N, --no-launch          Don't launch any CLI
  -e, --exec <cmd>         Custom CLI command

Options:
  -n, --dry-run            Show structure without writing
  -v, --verbose           Show detailed output
  -V, --version           Show version
  -h, --help              Show this help

Files:
  CLAUDE.md / AGENTS.md   Target files for injection (must exist)
  .vigilignore            Patterns to exclude (created if missing)
`)
}

func printVersion() {
	fmt.Printf("vigil %s\n", version)
}

func run(cfg *Config) error {
	root, err := filepath.Abs(cfg.RootDir)
	if err != nil {
		return fmt.Errorf("getting root path: %w", err)
	}

	projectName := filepath.Base(root)

	if cfg.Verbose {
		fmt.Printf("📂 Project: %s\n", projectName)
		fmt.Printf("📍 Root: %s\n", root)
	}

	// Ensure .vigilignore exists
	vigilIgnorePath := filepath.Join(root, ".vigilignore")
	if _, err := os.Stat(vigilIgnorePath); os.IsNotExist(err) {
		if err := os.WriteFile(vigilIgnorePath, []byte(defaultIgnore), 0644); err != nil {
			return fmt.Errorf("creating .vigilignore: %w", err)
		}
		if cfg.Verbose {
			fmt.Printf("✓ Created .vigilignore\n")
		}
	} else if cfg.Verbose {
		fmt.Printf("✓ Found .vigilignore\n")
	}

	// Find target files (CLAUDE.md or AGENTS.md)
	targets := findTargets(root)
	if len(targets) == 0 {
		return fmt.Errorf("no CLAUDE.md or AGENTS.md found in current directory")
	}

	if cfg.Verbose {
		fmt.Printf("📝 Target files:\n")
		for _, t := range targets {
			fmt.Printf("   - %s\n", filepath.Base(t))
		}
	}

	// Load exclusion patterns
	patterns, err := loadExclusionPatterns(root)
	if err != nil {
		return fmt.Errorf("loading patterns: %w", err)
	}

	if cfg.Verbose {
		fmt.Printf("🔒 Exclusion patterns: %d loaded\n", len(patterns))
	}

	// Generate tree structure
	structure, err := generateTree(root, patterns)
	if err != nil {
		return fmt.Errorf("generating tree: %w", err)
	}

	if cfg.Verbose {
		lines := strings.Count(structure, "\n")
		fmt.Printf("🌳 Generated tree: %d entries\n", lines-1) // -1 for project name line
	}

	if cfg.DryRun {
		fmt.Printf("\n```\n%s\n```\n", structure)
		return nil
	}

	// Inject into all target files
	for _, target := range targets {
		if err := injectStructure(target, structure, projectName); err != nil {
			return fmt.Errorf("injecting into %s: %w", filepath.Base(target), err)
		}
		if cfg.Verbose {
			fmt.Printf("✓ Injected structure into %s\n", filepath.Base(target))
		}
	}

	// Launch external CLI
	if cfg.ExecCmd != "" {
		if cfg.Verbose {
			fmt.Printf("🚀 Launching: %s\n", cfg.ExecCmd)
		}
		return launchCLI(cfg.ExecCmd, cfg.ExecArgs)
	}

	return nil
}

func findTargets(root string) []string {
	var targets []string

	for _, name := range []string{"CLAUDE.md", "AGENTS.md"} {
		path := filepath.Join(root, name)
		if _, err := os.Stat(path); err == nil {
			targets = append(targets, path)
		}
	}

	return targets
}

func loadExclusionPatterns(root string) ([]string, error) {
	var patterns []string

	if vigilPatterns, err := readFilePatterns(filepath.Join(root, ".vigilignore")); err == nil {
		patterns = append(patterns, vigilPatterns...)
	}

	if gitPatterns, err := readFilePatterns(filepath.Join(root, ".gitignore")); err == nil {
		patterns = append(patterns, gitPatterns...)
	}

	patterns = append(patterns, defaultExclusions...)
	return patterns, nil
}

func readFilePatterns(path string) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var patterns []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		patterns = append(patterns, line)
	}
	return patterns, scanner.Err()
}

func generateTree(root string, patterns []string) (string, error) {
	var entries []treeEntry

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}

		if path == root {
			return nil
		}

		relPath, err := filepath.Rel(root, path)
		if err != nil {
			return nil
		}

		if shouldExclude(relPath, d.IsDir(), patterns) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}

		depth := strings.Count(relPath, string(filepath.Separator))
		entries = append(entries, treeEntry{
			path:  relPath,
			isDir: d.IsDir(),
			depth: depth,
			name:  d.Name(),
		})

		return nil
	})

	if err != nil {
		return "", err
	}

	var buf strings.Builder
	buf.WriteString(filepath.Base(root) + "/\n\n")

	for _, e := range entries {
		indent := strings.Repeat("  ", e.depth)
		if e.isDir {
			buf.WriteString(fmt.Sprintf("%s%s/\n", indent, e.name))
		} else {
			buf.WriteString(fmt.Sprintf("%s%s\n", indent, e.name))
		}
	}

	return buf.String(), nil
}

func shouldExclude(path string, isDir bool, patterns []string) bool {
	normPath := filepath.ToSlash(path)
	parts := strings.Split(normPath, "/")

	for _, pattern := range patterns {
		normPattern := filepath.ToSlash(pattern)

		if strings.HasPrefix(normPattern, "/") {
			anchored := strings.TrimPrefix(normPattern, "/")
			if strings.HasPrefix(normPath, anchored) {
				return true
			}
			continue
		}

		if strings.HasSuffix(normPattern, "/") {
			dirName := strings.TrimSuffix(normPattern, "/")
			if isDir && (parts[len(parts)-1] == dirName || contains(parts, dirName)) {
				return true
			}
			continue
		}

		if strings.Contains(normPattern, "*") {
			if matchesGlob(parts[len(parts)-1], normPattern) {
				return true
			}
			for _, part := range parts {
				if matchesGlob(part, normPattern) {
					return true
				}
			}
			continue
		}

		if parts[len(parts)-1] == normPattern || contains(parts, normPattern) {
			return true
		}
	}

	return false
}

func matchesGlob(name, pattern string) bool {
	if strings.HasPrefix(pattern, "*.") {
		suffix := pattern[1:]
		return strings.HasSuffix(name, suffix)
	}
	if strings.HasPrefix(pattern, "*") {
		return strings.HasSuffix(name, pattern[1:])
	}
	if strings.HasSuffix(pattern, "*") {
		return strings.HasPrefix(name, pattern[:len(pattern)-1])
	}
	return name == pattern
}

func contains(slice []string, s string) bool {
	for _, item := range slice {
		if item == s {
			return true
		}
	}
	return false
}

func injectStructure(targetPath, structure, projectName string) error {
	content, err := os.ReadFile(targetPath)
	if err != nil {
		return err
	}

	contentStr := string(content)

	// Check if markers exist
	hasMarkers := strings.Contains(contentStr, markerStart) && strings.Contains(contentStr, markerEnd)

	var newSection string
	if hasMarkers {
		// Replace existing section
		startIdx := strings.Index(contentStr, markerStart)
		endIdx := strings.Index(contentStr, markerEnd) + len(markerEnd)

		// Find end of line after markerEnd
		remaining := contentStr[endIdx:]
		endOfLineIdx := strings.Index(remaining, "\n")
		if endOfLineIdx >= 0 {
			endIdx += endOfLineIdx + 1
		}

		newSection = fmt.Sprintf("%s\n\n## Project: %s\n\n```\n%s\n```\n%s\n",
			markerStart, projectName, strings.TrimSpace(structure), markerEnd)

		contentStr = contentStr[:startIdx] + newSection + contentStr[endIdx:]
	} else {
		// Append to end
		newSection = fmt.Sprintf("\n%s\n\n## Project: %s\n\n```\n%s\n```\n%s\n",
			markerStart, projectName, strings.TrimSpace(structure), markerEnd)
		contentStr = strings.TrimRight(contentStr, "\n") + newSection
	}

	return os.WriteFile(targetPath, []byte(contentStr), 0644)
}

func launchCLI(cmd string, args []string) error {
	var execCmd string
	var cmdArgs []string

	// Split command into parts (e.g., "claude --flag" -> ["claude", "--flag"])
	parts := strings.Fields(cmd)
	if len(parts) > 1 {
		execCmd = parts[0]
		cmdArgs = parts[1:]
	} else {
		execCmd = cmd
	}

	switch execCmd {
	case "claude":
		managedPath := filepath.Join(os.Getenv("HOME"), ".claude", "local", "claude")
		if _, err := os.Stat(managedPath); err == nil {
			execCmd = managedPath
		} else {
			execCmd = "claude"
		}
	case "aider":
		execCmd = "aider"
	case "cursor":
		execCmd = "cursor"
	case "opencode":
		execCmd = "opencode"
	case "openclaw":
		execCmd = "openclaw"
	case "hermes":
		execCmd = "hermes"
	case "droid":
		execCmd = "droid"
	case "crush":
		execCmd = "crush"
	case "goose":
		execCmd = "goose"
	}

	// Combine args from --exec string with positional args
	allArgs := append(cmdArgs, args...)

	c := exec.Command(execCmd, allArgs...)
	c.Stdin = os.Stdin
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr

	return c.Run()
}
